.Dd December 13 2023
.Dt EWCTL 1
.Os
.Sh NAME
.Nm ewctl
.Nd set display wallpaper
.Sh SYNOPSIS
.Nm
.Op Fl d Ar name
.Op Ar file
.Nm
.Fl h
.\" TODO
.Pp
The options are as follows:
.Bl -tag width Ds
.It Fl d , Fl Fl display Ns = Ns Ar name
.\" TODO
.It Fl h , Fl Fl help
.\" TODO
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
.\" TODO
.Sh SEE ALSO
.Xr convert 1 ,
.Xr ewd 1 ,
.Xr ImageMagick 1
.Sh AUTHORS
.An Thomas Voss Aq Mt mail@thomasvoss.com
